### ISSUE TITLE
Staff - Training Tab

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#16]
3rd Tab on Modal

Design NOTE - We will want to leave breadcrumbs to make it easy to get around to where you want to go unless you have a newer design that works too.

This will display all Trainings that Fire Fighter has been a part of it should persist the FF that I had in the basic tab and show their training history.  I should be able to see a list of the Title and Date - be able to click on said training and have a pop up display what that training was with lesson plan.

To differentiate between the other page for the Fire Fighter specifically with Certificates etc. with in the Training Module, This page is about Trainings attended for historical purposes ~and can also show certificate links~, but is intended for "admin"  You can click on one of the trainings and be shown the read only page being created in Card https://app.zenhub.com/workspace/o/incidentmanagementsystems/ims-issue-tracker/issues/62

When clicking on Fire Fighter name you should be presented with two options  1) Training List  2) ISO Summary (ISO Summary Blank until ISO part is completed) (separate story for ISO summary)

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/3042d942-e4cb-40f1-b7a2-2b2ff10afcc3)

**Comment by Sikta** [comment]
I'm hoping to make the same card work for both screens. I'm updating the current card to look like this instead. Will this work?

![image](https://user-images.githubusercontent.com/8400042/53781863-35e79580-3ed0-11e9-92a1-f637510d8144.png)

Some questions about the # of hours. For the full training list it makes sense to be the length of the training. For the fire fighters training list, should this be the length they were at the training? Should the start/end be the time they arrived/left instead of the trainings start/end? Do you want the value in decimal or would 2:15 be a better format?

**Comment by tfremming1** [comment]
For individual FF it should be length they were there.  99% of the time it will match the training time of the drill itself.  Decimal for time is fine e.g. 2.25.

excited to see it when you have it deployed.

**Comment by Sikta** [comment]
I'm gonna create a new story for the certificate uploads since I don't see such a story. I'm gonna add the management of certificates as a tab on the "staff detail" page.

**Comment by tfremming1** [comment]
Sounds good!
